# syntax=docker/dockerfile:1

FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Install Nest CLI globally (for running commands inside the container)
RUN npm install -g @nestjs/cli

ENV NODE_ENV development

# Expose the port
EXPOSE 3000

CMD [ "npm", "run", "start:dev" ]
